# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'coderay',     '1.1.1'
gem 'dotenv',      '2.2.1'
gem 'rspec',       '3.6.0'
gem 'taxjar-ruby', '1.7.0'
